[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

extend-safe-fixes = [
    "E501"
]
