messages_for_answering_questions = [
    "Processing...",
    "FAISS is optimized for efficient similarity search and clustering of dense vectors.",
    "Loading data and resources...",
    "Performing Named Entity Recognition (NER) on the input...",
    "Identifying key characteristics from the input...",
    "Parsing the question for relevant keywords...",
    "Vector indexes often use Euclidean distance for similarity measurement.",
    "Searching the FAISS index for similar data...",
    "Retrieving the most relevant results...",
    "FAISS uses various indexing methods for fast retrieval such as IVF (Inverted File) and HNSW (" "Hierarchical Navigable Small World).",
    "Comparing results to your question...",
    "Principal Component Analysis (PCA) can be used to reduce the dimensionality of vectors in FAISS.",
    "Generating a response with the LLM...",
    "FAISS supports GPU acceleration for improved performance.",
    "Validating the final output...",
    "Almost there...",
    "FAISS uses k-means clustering as one of its indexing techniques.",
    "Your response is ready!",
]

messages_for_getting_reviews = [
    "Fetching reviews...",
    "This code block uses semaphore to fetch reviews...",
    "A semaphore is a synchronization primitive used to control access to a common resource.",
    "Semaphores help manage concurrent access and prevent race conditions while looking up reviews.",
    "Looking up the product codes to review...",
    "Searching on the web with Selenium and Chrome for reviews...",
    "Selenium is a tool for automating web browsers.",
    "I am reading Grainger's sister company Zoro's website.",
    "That's because Grainger does not display reviews...yet???",
    "And on Zoro we sell a lot of the same products.",
    "Reading reviews...",
    "Polling is used to pass the data to the display."
    "Polling is a technique where a process repeatedly checks the status of an external condition.",
    "Averaging the review ratings...",
    "Collecting and reading review comments...",
    "Organizing the review comments to send to you.",
]
