apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: |-
    {{ .Values.aws_access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: |-
    {{ .Values.aws_secret_access_key | b64enc }}
  AWS_SESSION_TOKEN: |-
    {{ .Values.aws_session_token | b64enc }}
  BEDROCK_ASSUME_ROLE: |-
    {{ .Values.bedrock_assume_role | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: noelniko76/grainger_recommendations_chatbot:latest
        ports:
        - containerPort: 8501
        env:
        - name: PORT
          value: "8501"
        - name: AWS_REGION
          value: "${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SESSION_TOKEN
        - name: BEDROCK_ASSUME_ROLE
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: BEDROCK_ASSUME_ROLE
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 80  # The port on which the service will be accessible
    targetPort: 8505  # The port on which the application is listening inside the container
    nodePort: 30505  # The port on which the service will be exposed on each Node
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: streamlit.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit-service
            port:
              number: 80
