apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 80  # The port on which the service will be accessible
    targetPort: 8501  # The port on which the application is listening inside the container
    nodePort: 30505  # The port on which the service will be exposed on each Node
