apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: noelniko76/grainger_recommendations_chatbot:latest
        ports:
        - containerPort: 8501
        env:
        - name: PORT
          value: "8501"
