name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        pip install -r requirements.txt

    - name: Run Ruff linting
      run: |
        ruff check ./modules ./unit_tests
    

    - name: Run tests
      run: |
        pytest
